name: Netlify CI/CD # Name of the workflow.

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      my_env_var: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100 # Change to your version of .NET Core
    - name: Build
      working-directory: src
      run: dotnet build --configuration Release 
    - name: Publish 
      working-directory: src
      run: dotnet publish -c Release --no-build -o publishoutput
    - name: Deploy Preview
      if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
      uses: netlify/actions/cli@master
      env: # These are the environment variables added in GitHub Secrets for this repo
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
          args: deploy --dir=src/publishoutput/wwwroot # Push this folder to Netlify Preview
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
    - name: Deploy Production
      if: github.event_name != 'pull_request'
      uses: netlify/actions/cli@master
      env: # These are the environment variables added in GitHub Secrets for this repo
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
          args: deploy --dir=src/publishoutput/wwwroot --prod # Push this folder to Netlify Preview
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
